---
sudo: required
# group: bluezone
language: generic

# Environment variables (setup endpoint to IBM github   
env:
  global:
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

before_install: true
  # Clone build tools & set tools path for follow on processing 
  - if [[ ! -z "$BRANCH_OVERRIDE" ]] ; then
      git clone -b $BRANCH_OVERRIDE git@github.ibm.com:ibmprivatecloud/content-tools;
    else 
      git clone git@github.ibm.com:ibmprivatecloud/content-tools;
    fi
  - export toolsPath=`pwd`/content-tools/travis-tools/
  # Install dependencies & determine chart delta 
  - $toolsPath/build/bin/installDependencies.sh
  - export changeList=`$toolsPath/build/bin/determineChartDelta.sh | tee determineChartDelta.out | grep 'return determineChartDelta:' | cut -f2 -d:` && cat determineChartDelta.out
   
install: true
  # Package for release 
  - if [[ ! -z "$TRAVIS_TAG" ]] ; then $toolsPath/release/bin/package.sh; fi
  # Lint and install/test charts (if cv-tests exist)
  - $toolsPath/cv-test/bin/validateContent.sh

script: 
  - echo "Override default script"
  - stage: "Tests"                # naming the Tests stage
    name: "Unit Tests"            # names the first Tests stage job
    script: echo "./unit-tests"
  - script: echo "./integration-tests"   
    name: "Integration Tests"     # names the second Tests stage job
  - stage: deploy
    name: "Deploy to GCP"
    script: echo "./deploy  "

deploy: true
  # scp helm repo(s) to location identified (Note: SSHPASS env variable must contain password)
  - provider: script
    skip_cleanup: true
    script:  $toolsPath/build/bin/deployHelmRepo.sh
    on:
      all_branches: true
  # Publish tagged release
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: repo/stable/*
    on:
      tags: true
